"""Add embedding vector column to chunks
 
Revision ID: c229e935cec3
Revises: 20250602_0001
Create Date: 2026-06-09 12:53:54.622597
 
"""
from typing import Sequence, Union
 
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
 
# revision identifiers, used by Alembic.
revision: str = 'c229e935cec3'
down_revision: Union[str, None] = '20250602_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
 
    # Add embedding column to chunks (1536 dims for text-embedding-3-small)
    op.execute("ALTER TABLE chunks ADD COLUMN IF NOT EXISTS embedding vector(1536)")
 
    # Create ivfflat index for similarity search
    op.execute(
        "CREATE INDEX IF NOT EXISTS chunks_embedding_idx "
        "ON chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='Zero-based order of chunk within the parent email',
               existing_nullable=False)
    op.alter_column('chunks', 'token_count',
               existing_type=sa.INTEGER(),
               comment='Token count (tiktoken cl100k_base) for this chunk payload',
               existing_nullable=True)
    op.alter_column('emails', 'gmail_message_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Gmail API message id',
               existing_nullable=False)
    op.alter_column('emails', 'thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Gmail thread id for grouping conversation context',
               existing_nullable=True)
    op.alter_column('emails', 'body_plain',
               existing_type=sa.TEXT(),
               comment='Plaintext body only for MVP (no HTML parsing yet)',
               existing_nullable=True)
    op.alter_column('emails', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Message internal date from Gmail',
               existing_nullable=True)
    op.alter_column('emails', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Set when chunking/embedding pipeline completes',
               existing_nullable=True)
    op.alter_column('sync_jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', 'cancelled', name='sync_job_status'),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='sync_job_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=255),
               comment='Google OAuth subject identifier (stable user id from Google)',
               existing_nullable=False)
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    # Drop embedding index and column
    op.execute("DROP INDEX IF EXISTS chunks_embedding_idx")
    op.execute("ALTER TABLE chunks DROP COLUMN IF EXISTS embedding")
 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Google OAuth subject identifier (stable user id from Google)',
               existing_nullable=False)
    op.alter_column('sync_jobs', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='sync_job_status', native_enum=False),
               type_=postgresql.ENUM('pending', 'running', 'completed', 'failed', 'cancelled', name='sync_job_status'),
               existing_nullable=False)
    op.alter_column('emails', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Set when chunking/embedding pipeline completes',
               existing_nullable=True)
    op.alter_column('emails', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Message internal date from Gmail',
               existing_nullable=True)
    op.alter_column('emails', 'body_plain',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Plaintext body only for MVP (no HTML parsing yet)',
               existing_nullable=True)
    op.alter_column('emails', 'thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Gmail thread id for grouping conversation context',
               existing_nullable=True)
    op.alter_column('emails', 'gmail_message_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Gmail API message id',
               existing_nullable=False)
    op.alter_column('chunks', 'token_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Token count (tiktoken cl100k_base) for this chunk payload',
               existing_nullable=True)
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Zero-based order of chunk within the parent email',
               existing_nullable=False)
    # ### end Alembic commands ###